services:
  downloader:
    build: ./downloader
    restart: unless-stopped
    networks:
      - app-network

  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DOWNLOADER_API_URL: http://downloader:8899
    volumes:
      - ./data:/app/data
      - /root/cobalt:/root/cobalt
    depends_on:
      - downloader
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
